basePath: /
definitions:
  controller.metricsResponse:
    properties:
      activeContexts:
        type: integer
      activePages:
        type: integer
      isConnected:
        type: boolean
    type: object
host: localhost:3000
info:
  contact: {}
paths:
  /convert:
    post:
      consumes:
      - multipart/form-data
      description: Converts a URL or HTML to PDF document
      parameters:
      - description: URL
        in: formData
        name: url
        type: string
      - default: result.pdf
        description: Filename of the resulting pdf
        in: formData
        name: filename
        type: string
      - description: HTML to convert
        in: formData
        name: html
        type: string
      - default: en-US
        description: Page locale
        in: formData
        name: locale
        type: string
      - default: true
        description: Enable Javascript
        in: formData
        name: javascript
        type: boolean
      - default: A4
        description: Page format
        in: formData
        name: format
        type: string
      - default: false
        description: Disable network connectivity
        in: formData
        name: offline
        type: boolean
      - default: print
        description: Page media mode
        enum:
        - print
        - screen
        in: formData
        name: media
        type: string
      - description: Page margin top
        in: formData
        name: marginTop
        type: string
      - description: Page margin right
        in: formData
        name: marginRight
        type: string
      - description: Page margin bottom
        in: formData
        name: marginBottom
        type: string
      - description: Page footer template
        in: formData
        name: footerTemplate
        type: string
      - description: Page header template
        in: formData
        name: headerTemplate
        type: string
      produces:
      - application/pdf
      responses:
        "200":
          description: OK
          schema:
            type: file
      summary: Converts a URL or HTML to PDF document
      tags:
      - convert
  /metrics:
    get:
      description: Returns basic metrics about the server
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.metricsResponse'
      summary: Basic metrics endpoint
      tags:
      - metrics
  /ping:
    get:
      description: Check if the server is ready to accept requests
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: error
          schema:
            type: string
      summary: Check if the server is ready to accept requests
      tags:
      - ping
swagger: "2.0"
