on:
  push:
    paths-ignore:
      - "docs/**"
      - "*.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "*.md"

name: tests
env:
  GO111MODULE: on

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v2

      - name: Cache playwright client driver
        uses: actions/cache@v1
        with:
          path: ~/.cache/ms-playwright-go
          key: ${{ runner.os }}-playwright-go-${{ hashFiles('go.sum') }}
          restore-keys: ${{ runner.os }}-playwright-go-

      - name: Cache playwright client driver
        uses: actions/cache@v1
        with:
          path: ~/.cache/ms-playwright-go
          key: ${{ runner.os }}-playwright-${{ hashFiles('go.sum') }}
          restore-keys: ${{ runner.os }}-playwright-

      - name: Cache go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Build
        run: ./scripts/build.sh

      - name: Test
        run: ./scripts/test.sh
