on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: loadtesting
env:
  GO111MODULE: on

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v2

    - name: Cache playwright browsers
      uses: actions/cache@v1
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('go.sum') }}
        restore-keys: ${{ runner.os }}-playwright-

    - name: Cache go modules
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
        restore-keys: ${{ runner.os }}-go-

    - name: Run server with race detector
      run: go run -race cmd/fay/main.go &

    - name: Wait for server to be ready
      uses: nev7n/wait_for_response@v1.0.1
      with:
        url: 'http://localhost:3000/ping'
        responseCode: 200
        timeout: 2000
        interval: 250

    - name: Install k6
      run: |
        curl https://github.com/loadimpact/k6/releases/download/v0.29.0/k6-v0.29.0-linux64.tar.gz -L | tar xvz --strip-components 1

    - name: Run local k6 test
      run: |
        sleep 2000
        ./k6 run --env MAX_VUS=20 --env DURATION=5m --env BASE_URL=http://localhost:3000 ./loadtesting/html.js